[build]
  publish = "out"
  command = "npm ci --cache .npm --prefer-offline --retry=3 --timeout=300000 && npm run clean && npm run build:netlify"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  NEXT_TELEMETRY_DISABLED = "1"
  # 네트워크 안정성 향상
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_CONFIG_FETCH_RETRIES = "3"
  NPM_CONFIG_FETCH_RETRY_MINTIMEOUT = "10000"
  NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT = "60000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }