[build]
  publish = "out"
  command = "npm ci --cache .npm --prefer-offline && rm -rf .next out && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }